### ISSUE TITLE
Add time to completion

### ISSUE THREAD

**Issue by yourblackcat** [CheeseDanish1/Rosetta-Stone-Hack#2]
I was not able to find the authentication token or the session token to add to the program file so I used the second method in the video and it worked like a charm. However, the completion time of each activity is currently 1 minute. Is it possible to add time to the "time spent" column as well to avoid suspicion?

**Comment by zach-lim** [comment]
Ignore the above. I have managed to figure out how to use your program and it's working great! Is it possible to modify the program to read 100% program completion every single time?

**Comment by CheeseDanish1** [comment]
No problem. If you got the primary method to work, can you post a video of getting the information for the constants.json from the web requests? I would do it but I no longer have access to a Rosetta Stone account.

**Comment by yourblackcat** [comment]
I tried the same method but I am getting the following error when I run node index.js.

TypeError: Cannot convert argument to a ByteString because the character at index 512 has a value of 8230 which is greater than 255.
    at node:internal/deps/undici/undici:11754:11
    at async getData (/Users/me/Downloads/Rosetta-Stone-Hack-main/getData.js:7:15)
    at async main (/Users/me/Downloads/Rosetta-Stone-Hack-main/index.js:6:24)

Node.js v21.2.0

**Comment by yourblackcat** [comment]
After some trial and error, it appears that the full authorization token is found in the graphql file in the network tab of inspect element on chrome and the session token is found at the bottom of one of the scores files in the same tab. That should get everything working smoothly.

I'll make a video or write some detailed instructions with pictures this weekend.

**Comment by WJ0F** [comment]
did you ever upload that video

**Comment by WJ0F** [comment]
> After some trial and error, it appears that the error was caused by not having the full authorization token (the authorization token appears to be truncated on Firefox). The full auth token is found in the graphql file in the network tab of inspect element on chrome and the session token is found at the bottom of one of the scores files in the same tab. The search function is useful for these purposes. That should get everything working smoothly.
> 
> I do have one question though: can the program be updated to extend the completion time of the core lessons since these usually take a longer time to complete?
> 
> I'll update with a video or some detailed instructions with screenshots this weekend.

did you ever add a video/ screenshots

**Comment by Cubinster** [comment]
can you add the video pls

**Comment by Asiankidlol1** [comment]
> I was not able to find the authentication token or the session token to add to the program file so I used the second method in the video and it worked like a charm. However, the completion time of each activity is currently 1 minute. Is it possible to add time to the "time spent" column as well to avoid suspicion?

how did you fix the time spent?
